Repository wyfo/apischema, pull requests merged in 2021-05, with the labels that each got.

#114 Use textwrap.dedent for validator sources
  apischema/validation/dependencies.py
Labels: refactoring

#119 Replace schema extra example with strict union example
  docs/json_schema.md
  examples/schema_extra.py
  examples/strict_union.py
Labels: documentation

#124 Fix typo in graphql_schema
  apischema/graphql/schema.py
Labels: refactoring

#123 Fix Annotated handling in conversions
  apischema/graphql/relay/mutations.py
  apischema/graphql/resolvers.py
  apischema/serialization/serialized_methods.py
  apischema/utils.py
  apischema/validation/validators.py
Labels: refactoring

#131 Fix async resolver method not being handled as async
  apischema/graphql/relay/mutations.py
  apischema/graphql/resolvers.py
  apischema/utils.py
  tests/test_utils.py
Labels: bug

#130 Fix error raised in deserialization of resolver aliased parameters.
  apischema/graphql/resolvers.py
  tests/integration/test_aliased_resolvers.py
Labels: bug

#132 Fix get_type_hints issue on resolver parameter with None default
  apischema/graphql/resolvers.py
  tests/integration/test_aliased_resolvers.py
  tests/integration/test_resolver_default_parameter_not_serializable.py
Labels: bug

#133 Ignore Flake8 E501 because it's already handled by Black
  apischema/conversions/utils.py
  apischema/graphql/schema.py
  apischema/std_types.py
  setup.cfg
  setup.py
Labels: refactoring

#135 Handle annotated metadata directly in ObjectField
  apischema/graphql/resolvers.py
  apischema/graphql/schema.py
  apischema/objects/fields.py
  apischema/objects/utils.py
  apischema/objects/visitor.py
Labels: refactoring

#136 Fix dataclass_model deprecation message
  apischema/conversions/dataclass_models.py
Labels: refactoring
